# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
        - ::1
      trusted_users:
        192.168.1.0/24:
          - df752bdb3e8e43d982a05565b6959f4d # guest from .storage/auth
    - type: homeassistant

recorder:
  # secrets.yaml has recorder_db_url: mysql://hassuser:PASSWORD@localhost/hass_db
  db_url: !secret recorder_db_url
  commit_interval: 60
  purge_keep_days: 7
  include:
    entity_globs:
      - switch.*
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: disk_free
        arg: "/"
      - type: memory_use_percent
      - type: last_boot
