esphome:
  name: fan

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: high
  fast_connect: true
  reboot_timeout: 30s

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

switch:
  - platform: gpio
    pin: 23
    id: fan_power_switch
    name: "Fan Power Switch"
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: fan_power_switch
