# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
wifi_ssid: network_name
wifi_password: network_password
fallback_hotspot_password: hotspot_password
